### PR TITLE
feat: upgrade Zinnia to v0.20.0

### PR DESCRIPTION
**Pull request by bajtos**
https://github.com/filecoin-station/zinnia/releases/tag/v0.20.0

### CODE REVIEW

**Comment by juliangruber** [comment]
`Error: [zinnia] Cannot fetch binary linux x64: 404`

**Comment by bajtos** [comment]
There is a race condition in our GHA release workflow. Sometimes, two releases are created. Some of them receive artefacts for one subset of platforms, the other receives artefacts from the other subset.

**Comment by bajtos** [comment]
I am re-running the release build to see if it correctly uploads all artefacts to the same release. If not, then I can move the artefacts manually.

**Comment by bajtos** [comment]
All is green 🎉

**Pull request merged**
