### PR TITLE
Rotate Sentry DSN

### PR DESCRIPTION
**Pull request by juliangruber**

### CODE REVIEW

**Comment by bajtos** [comment]
FWIW, I have already rotated the token last week and disabled the old one.
See https://github.com/filecoin-station/core/pull/588

**Comment by bajtos** [comment]
I disabled the old token only yesterday, that's why the old error is still present in the weekly summary.

**Review by bajtos — APPROVED** [review]
Having said that, there is nothing wrong with this PR, we can land it if you like.

**Comment by juliangruber** [comment]
got it! Then this doesn't need to be released now

**Pull request merged**
